### ISSUE TITLE
Update sass/scss selector

### ISSUE THREAD

**Issue by rchl** [SublimeLinter/SublimeLinter-stylelint#10]
Newly released version of [Sass (SASS/SCSS syntax highlighting) package](https://github.com/braver/SublimeSass) standardised on using `style.css.sass` and `style.css.scss` keys instead of `style.sass` and `style.scss`. That means this linter will not trigger anymore with new syntax. We should add new selectors to the list (keep old for backwards compat).

@braver

**Comment by rchl** [comment]
Actually SASS is still using `source.sass`. Only SCSS changed from `source.scss` to `source.css.scss`.

**Comment by rchl** [comment]
Me again.
Actually the `style.css` selector is already included and so there should be no need to update anything.
I got confused because the `css` linter was triggering for me in scss file. Need to remove it.

**Comment by braver** [comment]
Yeah, there is no need for changes here, it's already covered by the existing selectors.
