### ISSUE TITLE
SublimeLinter: WARNING: stylelint: Defining 'cls.npm_name' has no effect. Please cleanup and remove these settings.

### ISSUE THREAD

**Issue by Svish** [SublimeLinter/SublimeLinter-stylelint#13]
Getting this warning after I install the SublimeLinter-stylelint package in Sublime Text 3:

> SublimeLinter: WARNING: stylelint: Defining 'cls.npm_name' has no effect. Please cleanup and remove these settings.

**Comment by wonkothesaner** [comment]
+1

**Comment by andreamoro** [comment]
Solutions?

**Comment by kaste** [comment]
For open source, PR's are always the solution 😁

**Comment by braver** [comment]
☝️

**Comment by kaste** [comment]
👏

**Comment by braver** [comment]
Well, and that's how it's done 😉
