### ISSUE TITLE
Linting css doesn't work SublimeText 4

### ISSUE THREAD

**Issue by s1mp7e** [SublimeLinter/SublimeLinter-stylelint#18]
Npm package "stylelint" installed local to work project folder. Files .stylelintrc.json and .stylelintignore lie at the root of the project.
In Sublime Text 4 installed your package SublimeLinter-stylelint. But on opening *.css files, linter doesn't work. Even with deliberate error. How to make linter friends with sublime text 4?

**Comment by kaste** [comment]
Hm, enable debug in the SublimeLinter settings, and take a look what we log here in the Sublime console.

**Comment by s1mp7e** [comment]
Ok, but how to do it? Where to find SublimeLinter settings? And does the Sublime Text have a console?

**Comment by braver** [comment]
We have a little website for these things: http://www.sublimelinter.com/en/stable/troubleshooting.html

ST has a really useful console, always a good place to start fixing problems 👌🏻

**Comment by s1mp7e** [comment]
Hello! There was time to tackle my problem. After installing the SublimeLinter-stylelint package, an error was displayed in the console related to the fact that the main SublimeLinter package was not installed. Installed it. Enabled debug mode in the settings. When you open the css file, the output is displayed in the console: "No installed linter matches the view". Again, the .stylelintrc.json file is in the project folder. The npm package "stylelint" is installed locally, also in the project folder. What are the ideas to solve my problem?

**Comment by kaste** [comment]
a) Either this plugin here is not installed or disabled (did you restart Sublime?), or b) you use a custom syntax for css files.  

For b), open the css file, hit `ctrl+shift+alt+p` which should open a tooltip showing a more or less complex scope.  Does the scope begin with `source.css`?

Upon starting Sublime, open the Sublime's console and make sure it re-loads "SublimeLinter" and "SublimeLinter-stylelint".  Open the SublimeLinter settings and make sure you did not configure anything for the stylelint linter, esp. you did not alter the `disable` setting.

**Comment by s1mp7e** [comment]
Only debug mode is enabled in SublimeLint settings. Does the scope begin with source.css? Yes, it starts with source.css. Console output at startup:

> reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin SublimeLinter-stylelint.linter
reloading python 3.3 plugin SublimeLinter.__init__
reloading python 3.3 plugin SublimeLinter._init
reloading python 3.3 plugin SublimeLinter.active_linters_view
reloading python 3.3 plugin SublimeLinter.busy_indicator_view
reloading python 3.3 plugin SublimeLinter.goto_commands
reloading python 3.3 plugin SublimeLinter.highlight_view
reloading python 3.3 plugin SublimeLinter.log_handler
reloading python 3.3 plugin SublimeLinter.message_view
reloading python 3.3 plugin SublimeLinter.panel_view
reloading python 3.3 plugin SublimeLinter.quick_actions
reloading python 3.3 plugin SublimeLinter.status_bar_view
reloading python 3.3 plugin SublimeLinter.sublime_linter
plugins loaded
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:74   debug mode: on
SublimeLinter: sublime_linter.py:75   version: 4.17.0
SublimeLinter: sublime_linter.py:345  Delay linting 'logo.css' for 0.0s
SublimeLinter: sublime_linter.py:361  No installed linter matches the view.

**Comment by kaste** [comment]
Difficult to tell what's going on here.  The "No installed linter matches the view." is an early check.  It does not depend on having a config or even having stylelint installed.  It just checks if there is any linter matching the scope of the view; before that it checks that the linter is *not* disabled, and that the file is not "excluded". Both "excludes" and "disable" are keys in the SublimeLinter settings and you say the SublimeLinter settings are empty except for the `debug` key.

Then the scope this linter here registers is `'source.css - meta.attribute-with-value, source.sass, source.scss, source.less, source.sss'` (also overridable via settings).  You can test if the view matches in the console:  Open and focus the css file, from here open the console, and type:

```
view.find_by_selector('source.css - meta.attribute-with-value, source.sass, source.scss, source.less, source.sss')
```

Hit `<enter>` and it should print something, a `Region`.  Make sure you have the correct `view` for example by executing

```
view.file_name()
```

in the console.

**Comment by kaste** [comment]
My hunch is that you have somewhere some settings overridden.  Maybe per project settings; per syntax settings, global Preferences...

**Comment by braver** [comment]
Closing since this looks like a user-specific issue we can't do much about.
