### ISSUE TITLE
Not compatible with Stylelint 14 ? 

### ISSUE THREAD

**Issue by oilvier** [SublimeLinter/SublimeLinter-stylelint#19]
Hi,

I'm under the impression that the plugin doesn't work with Stylelint ^14 ?

When I'm using the version 14.5.3 of Stylelint, SublimeLinter is showing me the prompt with "No lint results. Running stylelint." (even when I'm leaving errors on purpose).
It is as if the `.stylelintrc.json` file was not found or not understood.
There are no error in my `.stylelintrc.json` file because if I run Stylelint in CLI, the errors are showing as intended.

In the Sublime console, I got this message, but I don't know if it is related:

```
WARNING:SublimeLinter.plugin.stylelint:stylelint output:
(node:26109) ExperimentalWarning: The fs.promises API is experimental
(node:26109) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
TypeError: [configExtends].flat is not a function
    at extendConfig (/Users/[redacted]/node_modules/stylelint/lib/augmentConfig.js:196:44)
    at augmentConfigBasic (/Users/[redacted]/node_modules/stylelint/lib/augmentConfig.js:52:26)
    at augmentConfigFull (/Users/[redacted]/node_modules/stylelint/lib/augmentConfig.js:106:30)
    at Object.transform (/Users/[redacted]/node_modules/stylelint/lib/getConfigForFile.js:51:37)
    at run (/Users/[redacted]/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:42:49)

SublimeLinter: #17 linter.py:810      Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
INFO:SublimeLinter.plugin.stylelint:Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #17 linter.py:1220     stylelint: no output
INFO:SublimeLinter.plugin.stylelint:stylelint: no output
SublimeLinter: sublime_linter.py:593  Linting '_elements.page.scss' took 0.33s
INFO:SublimeLinter.sublime_linter:Linting '_elements.page.scss' took 0.33s
```

In the same project configuration, if I downgrade to Stylelint 13, SublimeLinter is prompting me the errors as expected.

As far as I know, with the 14 version Stylelint no longer includes the syntaxes for SCSS. Could it be the cause of the problem in SublimeLinter ?

**Comment by kaste** [comment]
Well, old issue.  `TypeError: [configExtends].flat is not a function` and the stacktrace that follows indicates that stylelint crashes completely.  `flat` not being available ("a function") indicates that you're running an older node version here.  So it is not SublimeLinter that is incompatible with version 14 but your nodejs is incompatible with your styleint version.  That's what I would read into this.  

Of course it is half a lie to say `No lint results` if the program crashes.  :shrug:  The comment ` Note: above warning will become an error in the future` obviously did not happen probably fear of breaking changes.  So the crashing just generates a warning not an error.

**Comment by oilvier** [comment]
That was indeed a problem with the nodeJS version used by Sublime Text.

Thanks !
