### ISSUE TITLE
Missing Configuration

### ISSUE THREAD

**Issue by CSM-800** [SublimeLinter/SublimeLinter-stylelint#20]
Get the plugin under MacOS just not to run because in the log always comes the error message that a configuration for stylint is missing. I have followed the instructions of stylelint but unfortunately did not work: https://stylelint.io/user-guide/get-started

I have entered in SublimeLinter the whole thing as a statement for the plugin. Does not work either. Who has the same problem and knows what exactly you have to do where?

**Comment by kaste** [comment]
What "whole thing" have you entered where?  Also enable debug in the settings, look at the console output then to be sure the working Dir for example is sane.

**Comment by CSM-800** [comment]
> What "whole thing" have you entered where? Also enable debug in the settings, look at the console output then to be sure the working Dir for example is sane.

Debug in SublimeLinter is active, that's where I got the error message.
Working path is output in the console and looks good.

Excerpt from the log.

>/Users/admin/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/name.agency/webseiten/name/wp-content/themes/name/assets/scss/layouts  (working dir)
  $ cat _pages-posts.scss | /usr/local/bin/stylelint --formatter json --stdin-filename /Users/admin/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/name.agency/webseiten/name/wp-content/themes/name/assets/scss/layouts/_pages-posts.scss
>
>SublimeLinter: #3 linter.py:809       WARNING: stylelint output:
Error: No configuration provided for /Users/admin/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/name.agency/webseiten/name/wp-content/themes/name/assets/scss/layouts/_pages-posts.scss
    at configurationError (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:11:49)
    at getConfigForFile (/usr/local/lib/node_modules/stylelint/lib/getConfigForFile.js:65:4)
    at async isPathIgnored (/usr/local/lib/node_modules/stylelint/lib/isPathIgnored.js:27:17)
    at async lintSource (/usr/local/lib/node_modules/stylelint/lib/lintSource.js:41:20)
    at async standalone (/usr/local/lib/node_modules/stylelint/lib/standalone.js:129:26)

In the SublimeLinter configuration I tried the following command:

>{
    "linters": {
        "stylelint":
        {
            "extends": "stylelint-config-standard"
        }    }
}

**Comment by kaste** [comment]
Ah.  The config doesn't go into the Sublime settings.  It has to be a file.

> 2. Create a .stylelintrc.json configuration file in the root of your project with the following content:
>
> ```
> {
>   "extends": "stylelint-config-standard"
> }
> ```

The SublimeLinter settings are to configure SublimeLinter.

**Comment by CSM-800** [comment]
> Ah. The config doesn't go into the Sublime settings. It has to be a file.
> 
> > 2. Create a .stylelintrc.json configuration file in the root of your project with the following content:
> > 
> > ```
> > {
> >   "extends": "stylelint-config-standard"
> > }
> > ```
> 
> The SublimeLinter settings are to configure SublimeLinter.

Thank you. Now it works.

And there is no way to store this once centrally somewhere without having to load it for each project now?

**Comment by kaste** [comment]
You can put a config file in a parent directory as stylelint traverses upwards until it finds one.

**Comment by CSM-800** [comment]
Good to know. Thanks again for the help.
