### ISSUE TITLE
Not possible to add command-line arguments

### ISSUE THREAD

**Issue by rgpublic** [SublimeLinter/SublimeLinter-stylelint#23]
In particular I'm missing a way to set the --config / -c option of stylelint, but perhaps it's more future-proof to add the option to add any arbitrary command-line arguments.

**Comment by kaste** [comment]
You should be able to use the args setting.  https://www.sublimelinter.com/en/latest/linter_settings.html#args. That is a common among all linters.

**Comment by rgpublic** [comment]
@kaste : Ah, yes. It works. Wonderful. Thanks a lot for the tip. Feeling a bit dumb that I didn't try that :-(
