### ISSUE TITLE
Doesn't support linter settings 'selector'

### ISSUE THREAD

**Issue by kevinmpowell** [SublimeLinter/SublimeLinter-stylelint#3]
In `Preferences.sublime-settings -- User` I've got:
```
...
"linters": {
  "stylelint": {
    "selector": "source.css - meta.attribute-with-value, source.less, source.sass, source.scss, source.postcss, source.pcss"
  }
}
```

but the linter won't invoke on `*.pcss` files when I open them with the [Syntax Highlighting for PostCSS plugin](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS)

If I instead open them with scss or CSS highlighting, the linter is invoked. This makes me think my `selector` override in user settings isn't being included since the [default selector](https://github.com/SublimeLinter/SublimeLinter-stylelint/blob/master/linter.py#L22) includes css and scss

**Comment by braver** [comment]
Adding `, source.postcss` to the default selector works for me (`source.pcss` is not something that exists as far as I know). I would need more debugging info to try and find what's the problem here.

**Comment by kaste** [comment]
Ad alert. My https://github.com/kaste/HighlightScopes makes this relatively easy.
