### ISSUE TITLE
Update 'cmd' string to support current stylelint CLI options

### ISSUE THREAD

**Issue by mattdeco** [SublimeLinter/SublimeLinter-stylelint#5]
Although I see similar discussion on #2 I was curious about the value of 'cmd' that is used to invoke stylelint.

Currently it looks like:

`stylelint --formatter json --stdin --stdin-filename ${file}`

However, it doesn't look like `--stdin` is a valid stylelint CLI option according to stylelint's help CLI output.

Alternatively, it can be updated to be something like this:

`stylelint "${file}" --formatter json ${args}`

This allows args to be passed from the linter definition in SublimeLinter.sublime-settings, something I dug into in the hopes of supporting the `--fix` flag so some basic CSS issues can be automatically fixed by stylelint.

There are probably good reasons why this is configured as such that I'm not aware of. Can you provide any info as to why `cmd` is structured like it is? If there is any flexibility here I'd be happy to submit a PR to update this so args can be passed to stylelint. Otherwise, feel free to close this issue.

Either way, thanks for the helpful SublimeLinter plugin!

**Comment by braver** [comment]
Could be the `stdin` flag is superfluous, haven’t checked.

About the —fix option, please read the discussion over at the eslint plugin: https://github.com/SublimeLinter/SublimeLinter-eslint/pull/254. I don’t think we’re going to support that, but you’re welcome to fork and make something for yourself.

**Comment by mattdeco** [comment]
Thank you for pointing me to that discussion and for the extra context, I'll keep an eye out for those changes to get released!
