### ISSUE TITLE
SublimeLinter 4 support?

### ISSUE THREAD

**Issue by pattiereaves** [SublimeLinter/SublimeLinter-stylelint#8]
This doesn't appear to work with SublimeLinter 4, which has been out for several months.

**Comment by braver** [comment]
Works well enough for me, what problems are you having with it?

**Comment by pattiereaves** [comment]
I was having issues but it may have been syntax changes with the settings
in the latest version of SublimeLinter, not this plugin. I noticed your
documentation says it requires SublimeLinter 3.




Pattie Reaves
Senior UX Developer, Alley Interactive
pattie@alley.co

**Comment by braver** [comment]
> I noticed your documentation says it requires SublimeLinter 3.

Oh, yeah, that's old. I see we missed a few of those. Anyway, this particular plugin should work since I use it every day. We did make some changes to project specific settings, so that maybe trips you up here.

**Comment by pattiereaves** [comment]
I figured out what was tripping me up — it was the new syntax for the
settings.

For the SublimeLinter ecosystem, it would be _so helpful_ to have an
example of what a preferences setup should look like, for user preferences
+ project settings.

**Comment by braver** [comment]
Well, we *do* have some docs with a handful of examples. If you see anything you think is missing, I'd really welcome a contribution!
