### ISSUE TITLE
Global installation support

### ISSUE THREAD

**Issue by horans** [SublimeLinter/SublimeLinter-stylelint#9]
Is it possible to install `postcss` and `stylelint` globally and make this linter work for all projects? (Similar as [htmlhint](https://github.com/htmlhint/SublimeLinter-contrib-htmlhint).)

I tried:

    npm install -g postcss stylelint

However sublime text will give warning as follow:

> SublimeLinter: WARNING: Stylelint crashed: No configuration provided...

**Comment by braver** [comment]
You can install the linter program globally, but it still needs to be able to find a configuration file. This, you can also make available globally by creating one in your home directory.  Please refer to postcss and stylelint documentation about creating these config files.
